apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins-custom
spec:
  source:
    git:
      uri:
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
      type: Source
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-custom:latest
